site_name: FPGA programming with OpenCL
nav:
  - Course description: 'index.md'
  - Introduction: 'intro.md'
  - OpenCL kernels: 'kernels.md'
  - Reporting & Profiling: 'rep_pro.md'
  - Kernel optimization: 'opt.md'
  - Channels & pipes: 'chan_pip.md'
  - References: 'references.md'
site_description: Webinar/Tutorial on how to use the Intel FPGA SDK
site_author: Emmanuel Kieffer
site_dir: public
site_url: "https://ekieffer.github.io/OpenCL-FPGA"

# Repository
repo_name: ekieffer/OpenCL-FPGA
repo_url: https://github.com/ekieffer/OpenCL-FPGA

# Copyright
copyright: Copyright &copy; 2023 E. Kieffer


# Configuration
# strict: true

theme:
  name: material
  language: en
    #  palette:
    #    primary: blue
    #    accent:  light blue
  features:
    - navigation.instant
  # #   - tabs

plugins:
  - search # necessary for search to work
  - git-revision-date-localized:
      type: date
  - progress
  - include-markdown

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ULHPC
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ULHPC

# Extra stylesheets (incl. Twitter Bootstrap)
extra_css:
  - stylesheets/extra.css
  # - stylesheets/bootstrap.min.css

# Extra javascript
extra_javascript:
  - javascripts/extra.js
  - javascripts/bootstrap.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js
  # https://squidfunk.github.io/mkdocs-material/reference/data-tables/#sortable-tables
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

# Extensions
markdown_extensions:
  - attr_list
  # notes, warnings, hints, ...
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - markdown_include.include:
      base_path: docs
  - markdown.extensions.admonition
  - meta
  - pymdownx.arithmatex
  - pymdownx.details
  # Icons from Emoji extensions, giving access to following icon sets:
  # - Material Design: https://materialdesignicons.com/
  # - FontAwesome:     https://fontawesome.com/icons?d=gallery&m=free
  # – Octicons:        https://octicons.github.com/
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # auto-link HTML, FTP, and email links
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true
  - pymdownx.snippets:
      base_path: snippets
  - pymdownx.tabbed
  - pymdownx.smartsymbols
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences
  - toc:
      permalink: true
